### ISSUE TITLE
有跨域请求的解决方案吗？

### ISSUE THREAD

**Issue by scstc** [oneone1995/M-Volunteer-SpringBoot#1]
有跨域请求的解决方案吗？

**Comment by turing1989** [comment]
有跨域请求的解决方案吗？

**Comment by oneone1995** [comment]
@turing1989 跨域请求是前端的知识吧？不好意思，我对前端知识不了解，帮不到您

**Comment by oneone1995** [comment]
@turing1989 了解到后端也是需要做相关配置才可以，可以使用@CrossOrigin注解或者可以写一个过滤器
